---
title: "Case_Study_4_Code"
author: "Brian Gaither, Sean Mcwhirter, Andrew Mejia, Sabrina Purvis"
date: "`r Sys.time()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 6
  github_document:
    toc: yes
    toc_depth: 6
  word_document:
    toc: yes
    toc_depth: '6'
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#This code is attributed to https://rdatasciencecases.org/CherryBlossom/code.R
#It has been adapted to suit class needs 

```{r}
library(tidyverse)
library(XML)
```

```{r}

#### Revised Text extractResTable Function
# Returns table from website in a character vector 

extractResTable =
  
  function(url = "http://www.cherryblossom.org/results/2009/09cucb-F.htm",
           year = 1999, sex = "male", file = NULL)
  {
    #added encoding for windows users who get an "A" symbol
    doc = htmlParse(url, encoding="UTF-8")
    
    if (year == 2000) {
      # Get preformatted text from 4th font element
      # The top file is ill formed so the <pre> search doesn't work.
      ff = getNodeSet(doc, "//font")
      txt = xmlValue(ff[[4]])
      els = strsplit(txt, "\r\n")[[1]]
    }
    else if (year == 2009 & sex == "male") {
      # Get preformatted text from <div class="Section1"> element
      # Each line of results is in a <pre> element
      div1 = getNodeSet(doc, "//div[@class='Section1']")
      pres = getNodeSet(div1[[1]], "//pre")
      els = sapply(pres, xmlValue)
    }
    
    else if (year == 1999 & sex == "male") { # have to add this else if statement
      # Get preformatted text from <pre> elements
      pres = getNodeSet(doc, "//pre")
      txt = xmlValue(pres[[1]])
      els = strsplit(txt, "\n")[[1]]   
    } 
    
    else {
      # Get preformatted text from <pre> elements
      pres = getNodeSet(doc, "//pre")
      txt = xmlValue(pres[[1]])
      els = strsplit(txt, "\r\n")[[1]]   
    } 
    
    if (is.null(file)) return(els)
    # Write the lines as a text file.
    writeLines(els, con = file)
  }


```

```{r}
### Base line url to be pasted 
ubase = "http://www.cherryblossom.org/"



#### Corrected URLS from new website
menURLs = 
  c("results/1999/cb99m.html",
    "results/2000/Cb003m.htm",
    "results/2001/oof_m.html", 
    "results/2002/oofm.htm", 
    "results/2003/CB03-M.HTM", 
    "results/2004/men.htm", 
    "results/2005/CB05-M.htm", 
    "results/2006/men.htm", 
    "results/2007/men.htm", 
    "results/2008/men.htm", 
    "results/2009/09cucb-M.htm",
    "results/2010/2010cucb10m-m.htm", 
    "results/2011/2011cucb10m-m.htm", 
    "results/2012/2012cucb10m-m.htm" 
  )

#### Paste all urls into a list 
urls = paste(ubase, menURLs, sep="")
urls[1:4]


#### Apply function from years 1999-2012 to scrape times 
years = 1999:2012
menTables = mapply(extractResTable, url = urls, year = years)
names(menTables) = years
sapply(menTables, length)

#### Confirm the format of the tables scraped 
menTables$'1999'[1:10]
menTables[[2]][1:10]

#### Save the outputs
save(menTables, file = "CBMenTextTables.rda")

#### Now we need to investigate the differences between the male and female result pages
# 2000
df_male_2000 <- extractResTable(url = "http://www.cherryblossom.org/results/2000/Cb003m.htm", year = 2000, sex = "male", file = NULL)
df_female_2000 <- extractResTable(url = "http://www.cherryblossom.org/results/2000/Cb003f.htm", year = 2000, sex = "female", file = NULL)

df_female_2000[1:10]
df_male_2000[1:10]

# 2006
df_male_2006 <- extractResTable(url = "http://www.cherryblossom.org/results/2006/men.htm", year = 2006, sex = "male", file = NULL)
df_female_2006 <- extractResTable(url = "http://www.cherryblossom.org/results/2006/women.htm", year = 2006, sex = "female", file = NULL)

df_female_2006[1:10]
df_male_2006[1:10]
```

```{r}
#### Corrected URLS from new website
womenURLs = 
  c("results/1999/cb99f.html",
    "results/2000/Cb003f.htm",
    "results/2001/oof_f.html", 
    "results/2002/ooff.htm", 
    "results/2003/CB03-F.HTM", 
    "results/2004/women.htm", 
    "results/2005/CB05-F.htm", 
    "results/2006/women.htm", 
    "results/2007/women.htm", 
    "results/2008/women.htm", 
    "results/2009/09cucb-F.htm",
    "results/2010/2010cucb10m-f.htm", 
    "results/2011/2011cucb10m-f.htm", 
    "results/2012/2012cucb10m-f.htm" 
  )

#### Paste all urls into a list 
urls = paste(ubase, womenURLs, sep="")
urls[1:4]


#### Apply function from years 1999-2012 to scrape times 
years = 1999:2012
womenTables = mapply(extractResTable, url = urls, year = years, sex = "female")
names(womenTables) = years
sapply(womenTables, length)

#### Confirm the format of the tables scraped 
womenTables$'1999'[1:10]
womenTables[[2]][1:10]

save(womenTables, file = "CBWomenTextTables.rda")


```
